name: ${name}
version: ${version}
main: ${group}.${name}
api-version: 1.21
author: FlyAwayMaking
website: https://github.com/flyawaymaking
description: Показывает координаты смерти игрока и редактирует сообщения о смерти

commands:
  deathmessages:
    description: Управление плагином DeathMessages
    usage: /<command> reload

  deathback:
    description: Телепортация к месту смерти
    usage: /<command> <deathId>

permissions:
  deathmessages.reload:
    description: Перезагрузка конфига плагина
    default: op

  deathmessages.dback:
    description: Возможность использовать телепортацию к месту смерти
    default: true
